name: Docker Build and Test

on: 
    # Trigger the workflow on push or pull request,
    # but only for the main branch.
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
jobs:
    build:
        name: Build Docker 
        runs-on: ubuntu-latest
        
        steps:
            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v1
              with:
                install: true

            - name: Run Buildx
              run: |
              docker build . # will run buildx